Create github action for posting slack announcements
DrizlyInc/slack-announce-action pull request #1
Opened 2021-09-14 13:26 UTC by benreynolds-drizly

2021-09-14 16:24 UTC, mikekantzer-drizly approved these changes
Looks good. Some things are _weird_, but perfectly fine. 


As a side note, you're exporting _every function and struct_ (they're capitalized)

This isn't too big of a problem, as we only have one package, but we'll need to keep an eye on that if we start breaking things up.


also, good eye on the tests.

2021-09-14 16:24 UTC, mikekantzer-drizly commented on action/inputs.go
> +func EnvOrFatal(name, msg string) string {
On the one hand, this is perfectly reasonable and I have no _actual_ objections. 

On the other hand, this feels wrong.

2021-09-14 16:24 UTC, mikekantzer-drizly commented on action/main.go
> +func GetColorAndTitleSuffix(status string) (string, string) {
Again, no _actual_ issues here, but i find this signature _weird_.

2021-09-14 16:29 UTC, jobimrobinsantos-drizly requested changes
I'm not qualified (yet) to review the golang parts, but I have some notes on the documentation

2021-09-14 16:29 UTC, jobimrobinsantos-drizly commented on README.md
> +        { "title": "`terraform-plan` on old-prod", "status": "${{ needs.terraform-plan-old-prod.result }}" },
Could you expand the usage section to include the full `job` context and include `needs` so that this part is more fully contextualized?

2021-09-14 16:29 UTC, jobimrobinsantos-drizly commented on README.md
> +    steps: |
Can you change the name of this parameter since `steps` already has a specific meaning in workflows?

2021-09-14 16:29 UTC, jobimrobinsantos-drizly commented on README.md
> +    # Status to be included in the message, from ${{ job.status }} ("success", "failure", or "cancelled")
Do we want to support "skipped" in the list of valid statuses?

2021-09-14 16:29 UTC, jobimrobinsantos-drizly commented on README.md
> +    # JSON array of { "title": "my title", "status": "my status" } objects to provide statuses of individual steps or jobs
Can you repeat the valid statuses here, too (also in action.yml)?

2021-09-14 19:19 UTC, benreynolds-drizly commented on README.md
> +    steps: |
Changed it to `indicators`

2021-09-14 19:33 UTC, benreynolds-drizly commented on README.md
> +    # Status to be included in the message, from ${{ job.status }} ("success", "failure", or "cancelled")
Added support for `skipped`

2021-09-14 21:16 UTC, ikatz-drizly commented on action/env.go
> +	githubRunNumber := EnvOrFatal("GITHUB_RUN_NUMBER", "Failed to read GITHUB_RUN_NUMBER from environment")
This seems like a lot of CTRL-C/CTRL-V just to verify that a set (array) of keys were present in the environment.  It should be replaced with iterating over an array of required env var names.

Separately, it looks like there is some per-field validation.  The repository wants to be in the form `/[^\/]+\/[^\/]+/` and `githubRunNumber` should probably be an integer.

2021-09-15 14:46 UTC, benreynolds-drizly commented on action/env.go
> +	githubRunNumber := EnvOrFatal("GITHUB_RUN_NUMBER", "Failed to read GITHUB_RUN_NUMBER from environment")
Iterating over an array would not allow me to assign each value to a struct property. It's not just validating presence, it's also returning the values for use throughout the rest of the action.

2021-09-15 14:49 UTC, benreynolds-drizly commented on action/main.go
> +func GetColorAndTitleSuffix(status string) (string, string) {
Split this into two separate methods.

2021-09-15 14:59 UTC, mikekantzer-drizly commented on action/env.go
> +	githubRunNumber := EnvOrFatal("GITHUB_RUN_NUMBER", "Failed to read GITHUB_RUN_NUMBER from environment")
You _could_ do something like 

```go
type Input struct {
name string
default string
error string
}
```

and then create a []Input, and then do a loop over it, and set values in Environment, 

but..... that gets fairly messy and annoying pretty quick. as-is, this is fine.

2021-09-15 15:04 UTC, mikekantzer-drizly approved these changes

2021-09-15 16:58 UTC, ikatz-drizly commented on action/env.go
> +	githubRunNumber := EnvOrFatal("GITHUB_RUN_NUMBER", "Failed to read GITHUB_RUN_NUMBER from environment")
That leaves the question about `githubRunNumber` being stored as a string.

I understand that the array iteration will not (cannot) populate the struct.  There seem to be 3 operations happening here 1. verify all inputs exist, fail with helpful error if not
2. verify that each input is in the correct format, fail with helpful error if not
3. fill the struct from the inputs, some of which are modified

Are there common libraries that can do at least some of this?  It looks very strange to invent our own.

2021-09-15 17:27 UTC, benreynolds-drizly commented on action/env.go
> +	githubRunNumber := EnvOrFatal("GITHUB_RUN_NUMBER", "Failed to read GITHUB_RUN_NUMBER from environment")
[This package](https://github.com/caarlos0/env) doesn't quite do everything we'd need but I added it for handling the basic parsing at least.

2021-09-17 15:45 UTC, jobimrobinsantos-drizly approved these changes
Changes to the README look good to me

2021-09-17 16:02 UTC, brettdugan-drizly commented on action/main.go
> +	}
Nitpick: If you're going to hardcode these, I wouldn't mind documenting what they should with constant names.
```suggestion
	const (
		green = "#4caf50"
		red   = "#f44336"
		gray  = "#808080"
	)
	switch status {
	case Success:
		return green
	case Failure:
		return red
	case Cancelled:
		return gray
	case Skipped:
		return gray
	default:
		githubactions.Fatalf("Provided status '%s' is invalid", status)
		return ""
	}	
```

2021-09-17 16:04 UTC, tatchley-drizly commented on action.yml
> +  channel:
* Does this action use Webhooks or a deeper Slack App integration? My (limited) understanding of [slack's incoming webhooks](https://api.slack.com/messaging/webhooks#advanced_message_formatting) was that each webhook was specific to an individual channel:
>  You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.
* If there is no restriction on Slack's side here, are we going to add in some restrictions on which repos can post where?

2021-09-17 16:07 UTC, benreynolds-drizly commented on .github/workflows/validate-and-release.yml
> +        uses: matootie/github-docker@v3.1.0
This one is built specifically to make using the github container registry easy whereas the docker one is more generic.

2021-09-17 16:09 UTC, benreynolds-drizly commented on action.yml
> +  channel:
There is no restriction on slack's side that I am aware of. I have tested it posting to multiple channels and it has worked fine. The username override also works. 

I don't think we can restrict which teams can post where either, particularly because this is open sourced and so we can't include any logic about drizly specific teams or slack channels.

2021-09-17 16:13 UTC, jobimrobinsantos-drizly commented on action.yml
> +  channel:
webhooks are channel-specific, but slack **apps** work differently; as long as you have the app credentials you can post to any channel where the app is "installed"

2021-09-17 16:17 UTC, brettdugan-drizly approved these changes

2021-09-17 16:19 UTC, merged